# sudo python2 XML_GetExcelForAFile.py Projects/libpng-code/pngwio.c 
# Identifier/program_domain.csv Projects/libpng-code/problem_domain.txt Projects/libpng-code_xml/pngwio_clang.xml libpng-code/pngwio.c

# FILES_TO_RUN = ['PLplot/src/plcont.c/plcont.c', 'PLplot/src/plvpor.c/plvpor.c', 'PLplot/src/plmem.c/plmem.c', 'PLplot/src/plsym.c/plsym.c', 'PLplot/src/plargs.c/plargs.c', 
# 'PLplot/src/plshade.c/plshade.c', 'PLplot/src/pltick.c/pltick.c', 'PLplot/src/plstripc.c/plstripc.c', 'PLplot/src/plwind.c/plwind.c', 'PLplot/src/plimage.c/plimage.c', 
# 'PLplot/src/plvect.c/plvect.c', 'PLplot/src/plarc.c/plarc.c', 'PLplot/src/plaffine.c/plaffine.c', 'PLplot/src/plcvt.c/plcvt.c', 'PLplot/src/plline.c/plline.c', 
# 'PLplot/src/plbox.c/plbox.c', 'PLplot/src/pltime.c/pltime.c', 'PLplot/src/plgridd.c/plgridd.c', 'PLplot/src/plgradient.c/plgradient.c', 'PLplot/src/plfill.c/plfill.c', 
# 'PLplot/src/plfreetype.c/plfreetype.c', 'PLplot/src/plot3d.c/plot3d.c', 'PLplot/src/plctrl.c/plctrl.c', 'PLplot/src/plcore.c/plcore.c', 'PLplot/src/mt19937ar.c/mt19937ar.c', 
# 'PLplot/src/plsdef.c/plsdef.c', 'PLplot/src/plbuf.c/plbuf.c', 'PLplot/src/plpage.c/plpage.c', 'PLplot/src/plhist.c/plhist.c', 'PLplot/src/pllegend.c/pllegend.c', 
# 'PLplot/src/plmetafile.c/plmetafile.c', 'PLplot/src/plmap.c/plmap.c',
# 'PLplot/src/plcont.c/plcont.c', 'PLplot/src/plvpor.c/plvpor.c', 'PLplot/src/plmem.c/plmem.c', 'PLplot/src/plsym.c/plsym.c', 'PLplot/src/plargs.c/plargs.c', 
# 'PLplot/src/plshade.c/plshade.c', 'PLplot/src/pltick.c/pltick.c', 'PLplot/src/plstripc.c/plstripc.c', 'PLplot/src/plwind.c/plwind.c', 'PLplot/src/plimage.c/plimage.c', 
# 'PLplot/src/plvect.c/plvect.c', 'PLplot/src/plarc.c/plarc.c', 'PLplot/src/plaffine.c/plaffine.c', 'PLplot/src/plcvt.c/plcvt.c', 'PLplot/src/plline.c/plline.c', 
# 'PLplot/src/plbox.c/plbox.c', 'PLplot/src/pltime.c/pltime.c', 'PLplot/src/plgridd.c/plgridd.c', 'PLplot/src/plgradient.c/plgradient.c', 'PLplot/src/plfill.c/plfill.c']

# FILES_TO_RUN = ['dealii/cmake/scripts/expand_instantiations.cc/expand_instantiations.cc',
#  'dealii/bundled/boost-1.62.0/libs/serialization/src/xml_iarchive.cpp/xml_iarchive.cpp',
#  'dealii/bundled/boost-1.62.0/libs/serialization/src/codecvt_null.cpp/codecvt_null.cpp',
#  'dealii/bundled/boost-1.62.0/libs/serialization/src/xml_grammar.cpp/xml_grammar.cpp',
#  'dealii/bundled/boost-1.62.0/libs/serialization/src/basic_text_iprimitive.cpp/basic_text_iprimitive.cpp',
#  'dealii/bundled/boost-1.62.0/libs/serialization/src/basic_pointer_iserializer.cpp/basic_pointer_iserializer.cpp',
#  'dealii/bundled/boost-1.62.0/libs/serialization/src/text_woarchive.cpp/text_woarchive.cpp',
#  'dealii/bundled/boost-1.62.0/libs/serialization/src/xml_archive_exception.cpp/xml_archive_exception.cpp',
#  'dealii/bundled/boost-1.62.0/libs/serialization/src/void_cast.cpp/void_cast.cpp',
#  'dealii/bundled/boost-1.62.0/libs/serialization/src/basic_iserializer.cpp/basic_iserializer.cpp',
#  'dealii/bundled/boost-1.62.0/libs/serialization/src/xml_wiarchive.cpp/xml_wiarchive.cpp',
#  'dealii/bundled/boost-1.62.0/libs/serialization/src/basic_pointer_oserializer.cpp/basic_pointer_oserializer.cpp',
#  'dealii/bundled/boost-1.62.0/libs/serialization/src/xml_wgrammar.cpp/xml_wgrammar.cpp',
#  'dealii/bundled/boost-1.62.0/libs/serialization/src/binary_iarchive.cpp/binary_iarchive.cpp',
#  'dealii/bundled/boost-1.62.0/libs/serialization/src/basic_text_woprimitive.cpp/basic_text_woprimitive.cpp',
#  'dealii/bundled/boost-1.62.0/libs/serialization/src/binary_woarchive.cpp/binary_woarchive.cpp',
#  'dealii/bundled/boost-1.62.0/libs/serialization/src/archive_exception.cpp/archive_exception.cpp',
#  'dealii/bundled/boost-1.62.0/libs/serialization/src/text_iarchive.cpp/text_iarchive.cpp',
#  'dealii/bundled/boost-1.62.0/libs/serialization/src/singleton.cpp/singleton.cpp',
#  'dealii/bundled/boost-1.62.0/libs/serialization/src/xml_woarchive.cpp/xml_woarchive.cpp',
#  'dealii/bundled/boost-1.62.0/libs/serialization/src/polymorphic_iarchive.cpp/polymorphic_iarchive.cpp',
#  'dealii/bundled/boost-1.62.0/libs/serialization/src/polymorphic_oarchive.cpp/polymorphic_oarchive.cpp',
#  'dealii/bundled/boost-1.62.0/libs/serialization/src/extended_type_info_typeid.cpp/extended_type_info_typeid.cpp',
#  'dealii/bundled/boost-1.62.0/libs/serialization/src/basic_archive.cpp/basic_archive.cpp',
#  'dealii/bundled/boost-1.62.0/libs/serialization/src/xml_oarchive.cpp/xml_oarchive.cpp',
#  'dealii/bundled/boost-1.62.0/libs/serialization/src/basic_serializer_map.cpp/basic_serializer_map.cpp',
#  'dealii/bundled/boost-1.62.0/libs/serialization/src/basic_iarchive.cpp/basic_iarchive.cpp',
#  'dealii/bundled/boost-1.62.0/libs/serialization/src/basic_xml_archive.cpp/basic_xml_archive.cpp',
#  'dealii/bundled/boost-1.62.0/libs/serialization/src/basic_oarchive.cpp/basic_oarchive.cpp',
#  'dealii/bundled/boost-1.62.0/libs/serialization/src/stl_port.cpp/stl_port.cpp',
#  'dealii/bundled/boost-1.62.0/libs/serialization/src/basic_oserializer.cpp/basic_oserializer.cpp',
#  'dealii/bundled/boost-1.62.0/libs/serialization/src/utf8_codecvt_facet.cpp/utf8_codecvt_facet.cpp',
#  'dealii/bundled/boost-1.62.0/libs/serialization/src/extended_type_info_no_rtti.cpp/extended_type_info_no_rtti.cpp',
#  'dealii/bundled/boost-1.62.0/libs/serialization/src/basic_text_oprimitive.cpp/basic_text_oprimitive.cpp',
#  'dealii/bundled/boost-1.62.0/libs/serialization/src/text_oarchive.cpp/text_oarchive.cpp',
#  'dealii/bundled/boost-1.62.0/libs/serialization/src/basic_text_wiprimitive.cpp/basic_text_wiprimitive.cpp',
#  'dealii/bundled/boost-1.62.0/libs/serialization/src/text_wiarchive.cpp/text_wiarchive.cpp',
#  'dealii/bundled/boost-1.62.0/libs/serialization/src/binary_wiarchive.cpp/binary_wiarchive.cpp',
#  'dealii/bundled/boost-1.62.0/libs/serialization/src/extended_type_info.cpp/extended_type_info.cpp',
#  'dealii/bundled/boost-1.62.0/libs/serialization/src/binary_oarchive.cpp/binary_oarchive.cpp',
#  'dealii/bundled/boost-1.62.0/libs/system/src/error_code.cpp/error_code.cpp',
#  'dealii/bundled/boost-1.62.0/libs/iostreams/src/file_descriptor.cpp/file_descriptor.cpp',
#  'dealii/bundled/boost-1.62.0/libs/iostreams/src/mapped_file.cpp/mapped_file.cpp',
#  'dealii/bundled/boost-1.62.0/libs/iostreams/src/gzip.cpp/gzip.cpp',
#  'dealii/bundled/boost-1.62.0/libs/iostreams/src/zlib.cpp/zlib.cpp',
#  'dealii/bundled/muparser_v2_2_4/src/muParserBase.cpp/muParserBase.cpp',
#  'dealii/bundled/muparser_v2_2_4/src/muParserCallback.cpp/muParserCallback.cpp',
#  'dealii/bundled/muparser_v2_2_4/src/muParserBytecode.cpp/muParserBytecode.cpp',
#  'dealii/bundled/muparser_v2_2_4/src/muParserTokenReader.cpp/muParserTokenReader.cpp',
#  'dealii/bundled/muparser_v2_2_4/src/muParser.cpp/muParser.cpp',
#  'dealii/bundled/muparser_v2_2_4/src/muParserInt.cpp/muParserInt.cpp',
#  'dealii/bundled/muparser_v2_2_4/src/muParserTest.cpp/muParserTest.cpp',
#  'dealii/bundled/muparser_v2_2_4/src/muParserError.cpp/muParserError.cpp',
#  'dealii/source/fe/fe_p1nc.cc/fe_p1nc.cc',
#  'dealii/source/fe/fe_dgp_monomial.cc/fe_dgp_monomial.cc',
#  'dealii/source/fe/fe_values_inst6.cc/fe_values_inst6.cc',
#  'dealii/source/fe/fe_q_hierarchical.cc/fe_q_hierarchical.cc',
#  'dealii/source/fe/fe_rt_bubbles.cc/fe_rt_bubbles.cc',
#  'dealii/source/fe/fe_dgp.cc/fe_dgp.cc',
#  'dealii/source/fe/mapping_q1_eulerian.cc/mapping_q1_eulerian.cc',
#  'dealii/source/fe/mapping_q_generic.cc/mapping_q_generic.cc',
#  'dealii/source/fe/fe_q_base.cc/fe_q_base.cc',
#  'dealii/source/fe/fe_data.cc/fe_data.cc',
#  'dealii/source/fe/fe_bernardi_raugel.cc/fe_bernardi_raugel.cc',
#  'dealii/source/fe/fe_nedelec_sz.cc/fe_nedelec_sz.cc',
#  'dealii/source/fe/fe_poly.cc/fe_poly.cc',
#  'dealii/source/fe/fe_series_fourier.cc/fe_series_fourier.cc',
#  'dealii/source/fe/fe_tools.cc/fe_tools.cc',
#  'dealii/source/fe/fe_raviart_thomas_nodal.cc/fe_raviart_thomas_nodal.cc',
#  'dealii/source/fe/fe_system.cc/fe_system.cc',
#  'dealii/source/fe/mapping.cc/mapping.cc',
#  'dealii/source/fe/fe_values_inst2.cc/fe_values_inst2.cc',
#  'dealii/source/fe/fe_enriched.cc/fe_enriched.cc',
#  'dealii/source/fe/mapping_q1.cc/mapping_q1.cc',
#  'dealii/source/fe/fe_q_iso_q1.cc/fe_q_iso_q1.cc',
#  'dealii/source/fe/fe_nedelec.cc/fe_nedelec.cc',
#  'dealii/source/fe/fe_abf.cc/fe_abf.cc',
#  'dealii/source/fe/fe_bernstein.cc/fe_bernstein.cc',
#  'dealii/source/fe/fe_rannacher_turek.cc/fe_rannacher_turek.cc',
#  'dealii/source/fe/mapping_q_eulerian.cc/mapping_q_eulerian.cc',
#  'dealii/source/fe/fe_dgq.cc/fe_dgq.cc',
#  'dealii/source/fe/fe_series_legendre.cc/fe_series_legendre.cc',
#  'dealii/source/fe/block_mask.cc/block_mask.cc',
#  'dealii/source/fe/fe_values_inst4.cc/fe_values_inst4.cc',
#  'dealii/source/fe/component_mask.cc/component_mask.cc',
#  'dealii/source/fe/fe_values_inst5.cc/fe_values_inst5.cc',
#  'dealii/source/fe/fe_poly_tensor.cc/fe_poly_tensor.cc',
#  'dealii/source/fe/fe_bdm.cc/fe_bdm.cc',
#  'dealii/source/fe/fe_q_bubbles.cc/fe_q_bubbles.cc',
#  'dealii/source/fe/mapping_c1.cc/mapping_c1.cc',
#  'dealii/source/fe/mapping_manifold.cc/mapping_manifold.cc',
#  'dealii/source/fe/fe_q_dg0.cc/fe_q_dg0.cc',
#  'dealii/source/fe/mapping_q.cc/mapping_q.cc',
#  'dealii/source/fe/fe_q.cc/fe_q.cc',
#  'dealii/source/fe/fe_values.cc/fe_values.cc',
#  'dealii/source/fe/fe_dgp_nonparametric.cc/fe_dgp_nonparametric.cc',
#  'dealii/source/fe/fe_values_extractors.cc/fe_values_extractors.cc',
#  'dealii/source/fe/fe_dg_vector.cc/fe_dg_vector.cc',
#  'dealii/source/fe/fe_series.cc/fe_series.cc',
#  'dealii/source/fe/fe_tools_extrapolate.cc/fe_tools_extrapolate.cc',
#  'dealii/source/fe/fe_face.cc/fe_face.cc',
#  'dealii/source/fe/fe_nothing.cc/fe_nothing.cc',
#  'dealii/source/fe/mapping_fe_field.cc/mapping_fe_field.cc',
#  'dealii/source/fe/fe_tools_interpolate.cc/fe_tools_interpolate.cc',
#  'dealii/source/fe/mapping_cartesian.cc/mapping_cartesian.cc',
#  'dealii/source/fe/fe_raviart_thomas.cc/fe_raviart_thomas.cc',
#  'dealii/source/fe/fe.cc/fe.cc',
#  'dealii/source/fe/fe_values_inst3.cc/fe_values_inst3.cc',
#  'dealii/source/fe/mapping_fe_field_inst2.cc/mapping_fe_field_inst2.cc',
#  'dealii/source/fe/fe_trace.cc/fe_trace.cc',
#  'dealii/source/dofs/dof_handler_policy.cc/dof_handler_policy.cc',
#  'dealii/source/dofs/block_info.cc/block_info.cc',
#  'dealii/source/dofs/number_cache.cc/number_cache.cc',
#  'dealii/source/dofs/dof_accessor_set.cc/dof_accessor_set.cc',
#  'dealii/source/dofs/dof_handler.cc/dof_handler.cc',
#  'dealii/source/dofs/dof_objects.cc/dof_objects.cc',
#  'dealii/source/dofs/dof_tools.cc/dof_tools.cc',
#  'dealii/source/dofs/dof_accessor.cc/dof_accessor.cc',
#  'dealii/source/dofs/dof_tools_sparsity.cc/dof_tools_sparsity.cc',
#  'dealii/source/dofs/dof_accessor_get.cc/dof_accessor_get.cc',
#  'dealii/source/dofs/dof_faces.cc/dof_faces.cc',
#  'dealii/source/dofs/dof_renumbering.cc/dof_renumbering.cc',
#  'dealii/source/dofs/dof_tools_constraints.cc/dof_tools_constraints.cc',
#  'dealii/source/numerics/solution_transfer_inst4.cc/solution_transfer_inst4.cc',
#  'dealii/source/numerics/matrix_creator_inst2.cc/matrix_creator_inst2.cc',
#  'dealii/source/numerics/vector_tools_project_hp.cc/vector_tools_project_hp.cc',
#  'dealii/source/numerics/histogram.cc/histogram.cc',
#  'dealii/source/numerics/data_out_stack.cc/data_out_stack.cc',
#  'dealii/source/numerics/vector_tools_project_inst3.cc/vector_tools_project_inst3.cc',
#  'dealii/source/numerics/error_estimator_1d.cc/error_estimator_1d.cc',
#  'dealii/source/numerics/vector_tools_interpolate.cc/vector_tools_interpolate.cc',
#  'dealii/source/numerics/vector_tools_project_qp.cc/vector_tools_project_qp.cc',
#  'dealii/source/numerics/dof_output_operator.cc/dof_output_operator.cc',
#  'dealii/source/numerics/matrix_tools.cc/matrix_tools.cc',
#  'dealii/source/numerics/error_estimator.cc/error_estimator.cc',
#  'dealii/source/numerics/vector_tools_mean_value.cc/vector_tools_mean_value.cc',
#  'dealii/source/numerics/vector_tools_integrate_difference.cc/vector_tools_integrate_difference.cc',
#  'dealii/source/numerics/data_out_rotation.cc/data_out_rotation.cc',
#  'dealii/source/numerics/solution_transfer.cc/solution_transfer.cc',
#  'dealii/source/numerics/data_out_dof_data.cc/data_out_dof_data.cc',
#  'dealii/source/numerics/fe_field_function.cc/fe_field_function.cc',
#  'dealii/source/numerics/data_out_dof_data_inst2.cc/data_out_dof_data_inst2.cc',
#  'dealii/source/numerics/solution_transfer_inst3.cc/solution_transfer_inst3.cc',
#  'dealii/source/numerics/matrix_creator.cc/matrix_creator.cc',
#  'dealii/source/numerics/data_postprocessor.cc/data_postprocessor.cc',
#  'dealii/source/numerics/vector_tools_rhs.cc/vector_tools_rhs.cc',
#  'dealii/source/numerics/data_out_faces.cc/data_out_faces.cc',
#  'dealii/source/numerics/vector_tools_boundary.cc/vector_tools_boundary.cc',
#  'dealii/source/numerics/point_value_history.cc/point_value_history.cc',
#  'dealii/source/numerics/vector_tools_project.cc/vector_tools_project.cc',
#  'dealii/source/numerics/matrix_creator_inst3.cc/matrix_creator_inst3.cc',
#  'dealii/source/numerics/kdtree.cc/kdtree.cc',
#  'dealii/source/numerics/vector_tools_constraints.cc/vector_tools_constraints.cc',
#  'dealii/source/numerics/vector_tools_point_value.cc/vector_tools_point_value.cc',
#  'dealii/source/numerics/vector_tools_project_codim.cc/vector_tools_project_codim.cc',
#  'dealii/source/numerics/matrix_tools_once.cc/matrix_tools_once.cc',
#  'dealii/source/numerics/vector_tools_project_qpmf.cc/vector_tools_project_qpmf.cc',
#  'dealii/source/numerics/data_out.cc/data_out.cc',
#  'dealii/source/numerics/time_dependent.cc/time_dependent.cc',
#  'dealii/source/numerics/error_estimator_inst2.cc/error_estimator_inst2.cc',
#  'dealii/source/numerics/derivative_approximation.cc/derivative_approximation.cc',
#  'dealii/source/numerics/data_out_dof_data_codim.cc/data_out_dof_data_codim.cc',
#  'dealii/source/numerics/solution_transfer_inst2.cc/solution_transfer_inst2.cc',
#  'dealii/source/numerics/vector_tools_point_gradient.cc/vector_tools_point_gradient.cc',
#  'dealii/source/numerics/vector_tools_project_inst2.cc/vector_tools_project_inst2.cc',
#  'dealii/source/sundials/ida.cc/ida.cc',
#  'dealii/source/sundials/copy.cc/copy.cc',
#  'dealii/source/sundials/arkode.cc/arkode.cc',
#  'dealii/source/sundials/kinsol.cc/kinsol.cc',
#  'dealii/source/lac/block_vector.cc/block_vector.cc',
#  'dealii/source/lac/affine_constraints.cc/affine_constraints.cc',
#  'dealii/source/lac/block_sparse_matrix_ez.cc/block_sparse_matrix_ez.cc',
#  'dealii/source/lac/block_sparsity_pattern.cc/block_sparsity_pattern.cc',
#  'dealii/source/lac/block_matrix_array.cc/block_matrix_array.cc',
#  'dealii/source/lac/block_sparse_matrix.cc/block_sparse_matrix.cc']

# FILES_TO_RUN = ['curl/tests/server/testpart.c/testpart.c', 'curl/tests/server/util.c/util.c', 'curl/tests/server/sws.c/sws.c', 'curl/tests/server/getpart.c/getpart.c', 'curl/tests/server/disabled.c/disabled.c', 'curl/tests/server/rtspd.c/rtspd.c', 'curl/tests/server/tftpd.c/tftpd.c', 'curl/tests/server/fake_ntlm.c/fake_ntlm.c', 'curl/tests/server/sockfilt.c/sockfilt.c', 'curl/tests/libtest/lib537.c/lib537.c', 'curl/tests/libtest/lib554.c/lib554.c', 'curl/tests/libtest/lib599.c/lib599.c', 'curl/tests/libtest/lib1512.c/lib1512.c', 'curl/tests/libtest/lib567.c/lib567.c', 'curl/tests/libtest/lib1156.c/lib1156.c', 'curl/tests/libtest/lib659.c/lib659.c', 'curl/tests/libtest/lib574.c/lib574.c', 'curl/tests/libtest/lib553.c/lib553.c', 'curl/tests/libtest/lib541.c/lib541.c', 'curl/tests/libtest/lib1514.c/lib1514.c', 'curl/tests/libtest/first.c/first.c', 'curl/tests/libtest/chkdecimalpoint.c/chkdecimalpoint.c', 'curl/tests/libtest/lib1537.c/lib1537.c', 'curl/tests/libtest/lib1536.c/lib1536.c', 'curl/tests/libtest/lib598.c/lib598.c', 'curl/tests/libtest/lib559.c/lib559.c', 'curl/tests/libtest/lib1506.c/lib1506.c', 'curl/tests/libtest/lib1509.c/lib1509.c', 'curl/tests/libtest/lib1538.c/lib1538.c', 'curl/tests/libtest/libntlmconnect.c/libntlmconnect.c', 'curl/tests/libtest/lib558.c/lib558.c', 'curl/tests/libtest/lib523.c/lib523.c', 'curl/tests/libtest/lib1550.c/lib1550.c', 'curl/tests/libtest/lib1556.c/lib1556.c', 'curl/tests/libtest/lib525.c/lib525.c', 'curl/tests/libtest/lib1564.c/lib1564.c', 'curl/tests/libtest/lib1526.c/lib1526.c', 'curl/tests/libtest/lib1520.c/lib1520.c', 'curl/tests/libtest/lib549.c/lib549.c', 'curl/tests/libtest/lib1511.c/lib1511.c', 'curl/tests/libtest/sethostname.c/sethostname.c', 'curl/tests/libtest/lib539.c/lib539.c', 'curl/tests/libtest/lib568.c/lib568.c', 'curl/tests/libtest/lib583.c/lib583.c', 'curl/tests/libtest/lib543.c/lib543.c', 'curl/tests/libtest/lib654.c/lib654.c', 'curl/tests/libtest/lib575.c/lib575.c', 'curl/tests/libtest/lib1554.c/lib1554.c', 'curl/tests/libtest/lib513.c/lib513.c', 'curl/tests/libtest/lib1533.c/lib1533.c', 'curl/tests/libtest/lib547.c/lib547.c', 'curl/tests/libtest/lib1541.c/lib1541.c', 'curl/tests/libtest/lib643.c/lib643.c', 'curl/tests/libtest/lib582.c/lib582.c',
# 'curl/tests/libtest/lib582.c/lib582.c', 'curl/src/tool_getparam.c/tool_getparam.c', 'curl/src/tool_metalink.c/tool_metalink.c', 'curl/src/tool_homedir.c/tool_homedir.c', 'curl/src/tool_cb_prg.c/tool_cb_prg.c', 'curl/src/tool_bname.c/tool_bname.c', 'curl/src/tool_help.c/tool_help.c', 'curl/src/tool_cb_hdr.c/tool_cb_hdr.c', 'curl/src/tool_operhlp.c/tool_operhlp.c', 'curl/lib/imap.c/imap.c', 'curl/lib/hostcheck.c/hostcheck.c', 'curl/lib/ftplistparser.c/ftplistparser.c', 'curl/lib/vauth/digest.c/digest.c', 'curl/lib/vauth/vauth.c/vauth.c', 'curl/lib/vauth/digest_sspi.c/digest_sspi.c', 'curl/lib/vauth/ntlm_sspi.c/ntlm_sspi.c', 'curl/lib/vauth/cram.c/cram.c', 'curl/lib/vauth/spnego_sspi.c/spnego_sspi.c', 'curl/lib/vauth/krb5_sspi.c/krb5_sspi.c', 'curl/lib/vauth/oauth2.c/oauth2.c', 'curl/lib/vauth/cleartext.c/cleartext.c', 'curl/lib/vauth/spnego_gssapi.c/spnego_gssapi.c', 'curl/lib/curl_memrchr.c/curl_memrchr.c', 'curl/lib/curl_path.c/curl_path.c',
# 'curl/lib/imap.c/imap.c', 'curl/lib/hostcheck.c/hostcheck.c', 'curl/lib/ftplistparser.c/ftplistparser.c', 'curl/lib/vauth/digest.c/digest.c', 'curl/lib/vauth/vauth.c/vauth.c', 'curl/lib/vauth/digest_sspi.c/digest_sspi.c', 'curl/lib/vauth/ntlm_sspi.c/ntlm_sspi.c', 'curl/lib/vauth/cram.c/cram.c', 'curl/lib/vauth/spnego_sspi.c/spnego_sspi.c', 'curl/lib/vauth/krb5_sspi.c/krb5_sspi.c', 'curl/lib/vauth/oauth2.c/oauth2.c', 'curl/lib/vauth/cleartext.c/cleartext.c', 'curl/lib/vauth/spnego_gssapi.c/spnego_gssapi.c', 'curl/lib/curl_memrchr.c/curl_memrchr.c', 'curl/lib/curl_path.c/curl_path.c', 'curl/lib/security.c/security.c', 'curl/lib/hostasyn.c/hostasyn.c', 'curl/lib/http2.c/http2.c', 'curl/lib/strdup.c/strdup.c', 'curl/lib/asyn-thread.c/asyn-thread.c', 'curl/lib/transfer.c/transfer.c', 'curl/lib/content_encoding.c/content_encoding.c', 'curl/lib/timeval.c/timeval.c', 'curl/lib/dict.c/dict.c', 'curl/lib/socks_gssapi.c/socks_gssapi.c', 'curl/lib/doh.c/doh.c', 'curl/lib/rtsp.c/rtsp.c', 'curl/lib/gopher.c/gopher.c', 'curl/lib/curl_sasl.c/curl_sasl.c', 'curl/lib/x509asn1.c/x509asn1.c', 'curl/lib/file.c/file.c', 'curl/lib/formdata.c/formdata.c', 'curl/lib/tftp.c/tftp.c', 'curl/lib/mime.c/mime.c', 'curl/lib/http.c/http.c', 'curl/lib/hostsyn.c/hostsyn.c', 'curl/lib/openldap.c/openldap.c', 'curl/lib/select.c/select.c', 'curl/lib/http_chunks.c/http_chunks.c', 'curl/lib/splay.c/splay.c', 'curl/lib/curl_fnmatch.c/curl_fnmatch.c', 'curl/lib/vquic/ngtcp2.c/ngtcp2.c', 'curl/lib/asyn-ares.c/asyn-ares.c', 'curl/lib/escape.c/escape.c',
# 'curl/tests/server/sockfilt.c/sockfilt.c', 'curl/tests/libtest/lib537.c/lib537.c', 'curl/tests/libtest/lib554.c/lib554.c', 'curl/tests/libtest/lib599.c/lib599.c', 'curl/tests/libtest/lib1512.c/lib1512.c', 'curl/tests/libtest/lib567.c/lib567.c', 'curl/tests/libtest/lib1156.c/lib1156.c', 'curl/tests/libtest/lib659.c/lib659.c', 'curl/tests/libtest/lib574.c/lib574.c', 'curl/tests/libtest/lib553.c/lib553.c', 'curl/tests/libtest/lib541.c/lib541.c', 'curl/tests/libtest/lib1514.c/lib1514.c', 'curl/tests/libtest/first.c/first.c', 'curl/tests/libtest/chkdecimalpoint.c/chkdecimalpoint.c', 'curl/tests/libtest/lib1537.c/lib1537.c', 'curl/tests/libtest/lib1536.c/lib1536.c', 'curl/tests/libtest/lib598.c/lib598.c', 'curl/tests/libtest/lib559.c/lib559.c', 'curl/tests/libtest/lib1506.c/lib1506.c', 'curl/tests/libtest/lib1509.c/lib1509.c', 'curl/tests/libtest/lib1538.c/lib1538.c', 'curl/tests/libtest/libntlmconnect.c/libntlmconnect.c', 'curl/tests/libtest/lib558.c/lib558.c', 'curl/tests/libtest/lib523.c/lib523.c', 'curl/tests/libtest/lib1550.c/lib1550.c', 'curl/tests/libtest/lib1556.c/lib1556.c', 'curl/tests/libtest/lib525.c/lib525.c', 'curl/tests/libtest/lib1564.c/lib1564.c', 'curl/tests/libtest/lib1526.c/lib1526.c', 'curl/tests/libtest/lib1520.c/lib1520.c', 'curl/tests/libtest/lib549.c/lib549.c', 'curl/tests/libtest/lib1511.c/lib1511.c', 'curl/tests/libtest/sethostname.c/sethostname.c', 'curl/tests/libtest/lib539.c/lib539.c', 'curl/tests/libtest/lib568.c/lib568.c', 'curl/tests/libtest/lib583.c/lib583.c', 'curl/tests/libtest/lib543.c/lib543.c', 'curl/tests/libtest/lib654.c/lib654.c', 'curl/tests/libtest/lib575.c/lib575.c', 'curl/tests/libtest/lib1554.c/lib1554.c', 'curl/tests/libtest/lib513.c/lib513.c', 'curl/tests/libtest/lib1533.c/lib1533.c', 'curl/tests/libtest/lib547.c/lib547.c', 'curl/tests/libtest/lib1541.c/lib1541.c', 'curl/tests/libtest/lib643.c/lib643.c', 'curl/tests/libtest/lib582.c/lib582.c']

FILES_TO_RUN = ['repos/server_mariadb/extra/readline/signals.c', 'repos/server_mariadb/extra/readline/histexpand.c', 'repos/server_mariadb/extra/readline/kill.c', 'repos/server_mariadb/extra/readline/histfile.c', 'repos/server_mariadb/extra/readline/emacs_keymap.c', 'repos/server_mariadb/extra/readline/text.c', 'repos/server_mariadb/extra/readline/bind.c', 'repos/server_mariadb/extra/readline/undo.c', 'repos/server_mariadb/extra/readline/histsearch.c', 'repos/server_mariadb/extra/readline/savestring.c', 'repos/server_mariadb/extra/readline/callback.c', 'repos/server_mariadb/extra/readline/complete.c', 'repos/server_mariadb/extra/readline/mbutil.c', 'repos/server_mariadb/extra/readline/input.c', 'repos/server_mariadb/extra/readline/keymaps.c', 'repos/server_mariadb/extra/readline/tilde.c', 'repos/server_mariadb/extra/readline/isearch.c', 'repos/server_mariadb/extra/readline/vi_keymap.c',
'repos/server_mariadb/extra/readline/macro.c', 'repos/server_mariadb/extra/readline/compat.c', 'repos/server_mariadb/extra/readline/shell.c', 'repos/server_mariadb/extra/readline/terminal.c', 'repos/server_mariadb/extra/readline/readline.c', 'repos/server_mariadb/extra/readline/history.c', 'repos/server_mariadb/extra/readline/funmap.c', 'repos/server_mariadb/extra/mariabackup/ds_stdout.cc', 'repos/server_mariadb/extra/mariabackup/xbstream_read.cc', 'repos/server_mariadb/extra/mariabackup/ds_tmpfile.cc', 'repos/server_mariadb/extra/mariabackup/ds_archive.cc', 'repos/server_mariadb/extra/mariabackup/datasink.cc', 'repos/server_mariadb/extra/mariabackup/ds_compress.cc', 'repos/server_mariadb/extra/mariabackup/wsrep.cc', 'repos/server_mariadb/extra/mariabackup/ds_local.cc', 'repos/server_mariadb/extra/mariabackup/fil_cur.cc', 'repos/server_mariadb/extra/mariabackup/backup_copy.cc', 'repos/server_mariadb/extra/mariabackup/read_filt.cc', 'repos/server_mariadb/extra/mariabackup/ds_buffer.cc', 'repos/server_mariadb/extra/mariabackup/write_filt.cc', 'repos/server_mariadb/extra/mariabackup/encryption_plugin.cc', 'repos/server_mariadb/extra/mariabackup/changed_page_bitmap.cc', 'repos/server_mariadb/extra/mariabackup/innobackupex.cc', 'repos/server_mariadb/extra/mariabackup/xbstream.cc', 'repos/server_mariadb/extra/mariabackup/backup_mysql.cc', 'repos/server_mariadb/extra/mariabackup/xbcloud.cc', 'repos/server_mariadb/extra/mariabackup/xtrabackup.cc', 'repos/server_mariadb/extra/mariabackup/xbstream_write.cc', 'repos/server_mariadb/extra/mariabackup/ds_xbstream.cc', 'repos/server_mariadb/extra/mariabackup/crc/crc_glue.c', 'server_mariadb_winter_annotation/sql-common/client_plugin.c', 'server_mariadb_winter_annotation/sql-common/my_user.c', 'server_mariadb_winter_annotation/sql-common/conf_to_src.c', 'server_mariadb_winter_annotation/sql-common/mysql_async.c', 'server_mariadb_winter_annotation/sql-common/errmsg.c', 'server_mariadb_winter_annotation/sql-common/client.c', 'server_mariadb_winter_annotation/sql-common/pack.c', 'server_mariadb_winter_annotation/sql-common/my_time.c', 'server_mariadb_winter_annotation/libmariadb/zlib/gzwrite.c', 'server_mariadb_winter_annotation/libmariadb/zlib/inffast.c', 'server_mariadb_winter_annotation/libmariadb/zlib/zutil.c', 'server_mariadb_winter_annotation/libmariadb/zlib/infback.c', 'server_mariadb_winter_annotation/libmariadb/zlib/example.c', 'server_mariadb_winter_annotation/libmariadb/zlib/compress.c', 'server_mariadb_winter_annotation/libmariadb/zlib/adler32.c', 'server_mariadb_winter_annotation/libmariadb/zlib/crc32.c', 'server_mariadb_winter_annotation/libmariadb/zlib/gzread.c', 'server_mariadb_winter_annotation/libmariadb/zlib/inflate.c', 'server_mariadb_winter_annotation/libmariadb/zlib/inftrees.c', 'server_mariadb_winter_annotation/libmariadb/zlib/deflate.c',
'repos/server_mariadb/extra/readline/terminal.c', 'repos/server_mariadb/extra/readline/readline.c', 'repos/server_mariadb/extra/readline/history.c', 'repos/server_mariadb/extra/readline/funmap.c', 'repos/server_mariadb/extra/mariabackup/ds_stdout.cc', 'repos/server_mariadb/extra/mariabackup/xbstream_read.cc', 'repos/server_mariadb/extra/mariabackup/ds_tmpfile.cc', 'repos/server_mariadb/extra/mariabackup/ds_archive.cc', 'repos/server_mariadb/extra/mariabackup/datasink.cc', 'repos/server_mariadb/extra/mariabackup/ds_compress.cc', 'repos/server_mariadb/extra/mariabackup/wsrep.cc', 'repos/server_mariadb/extra/mariabackup/ds_local.cc', 'repos/server_mariadb/extra/mariabackup/fil_cur.cc', 'repos/server_mariadb/extra/mariabackup/backup_copy.cc', 'repos/server_mariadb/extra/mariabackup/read_filt.cc', 'repos/server_mariadb/extra/mariabackup/ds_buffer.cc', 'repos/server_mariadb/extra/mariabackup/write_filt.cc', 'repos/server_mariadb/extra/mariabackup/encryption_plugin.cc', 'repos/server_mariadb/extra/mariabackup/changed_page_bitmap.cc']

import os

BASE_DIR = "Projects/server/"

def PJ(dir):
	return os.path.join(BASE_DIR,dir)

for file in set(FILES_TO_RUN):
	# if file in FILES_ALREADY_RUN:
	# 	continue
	basename = os.path.basename(file)
	file_without_extention = basename.split(".")[0]
	complete_path_file = PJ(file[len('repos/server_mariadb/'):])
	if os.path.exists("CSV/"+complete_path_file.replace("/","_")+"_train.csv"):
		print("SKIPPING - ",complete_path_file)
		continue
	complete_path_xml = os.path.join("DATA",complete_path_file)
	complete_path_xml = complete_path_xml.split(".")[0]
	complete_path_xml += "_clang.xml"
	print("Running for file - ",file, complete_path_file, complete_path_xml)
	print("HETE ->",complete_path_file)
	os.system("python2 XML_GetExcelForAFile.py " + complete_path_file + " Identifier/program_domain.csv ProblemDomains/problem_domain_mariaDB.txt " +complete_path_xml + " " + file)

# Run inside CSV folder

# import shutil
# import os
# for file in os.listdir("."):
# 	if file.startswith(".._.._"):
# 		shutil.copy(file,file[6:])