# sudo python2 XML_GetExcelForAFile.py Projects/libpng-code/pngwio.c 
# Identifier/program_domain.csv Projects/libpng-code/problem_domain.txt Projects/libpng-code_xml/pngwio_clang.xml libpng-code/pngwio.c

# FILES_TO_RUN = ['PLplot/src/plcont.c/plcont.c', 'PLplot/src/plvpor.c/plvpor.c', 'PLplot/src/plmem.c/plmem.c', 'PLplot/src/plsym.c/plsym.c', 'PLplot/src/plargs.c/plargs.c', 
# 'PLplot/src/plshade.c/plshade.c', 'PLplot/src/pltick.c/pltick.c', 'PLplot/src/plstripc.c/plstripc.c', 'PLplot/src/plwind.c/plwind.c', 'PLplot/src/plimage.c/plimage.c', 
# 'PLplot/src/plvect.c/plvect.c', 'PLplot/src/plarc.c/plarc.c', 'PLplot/src/plaffine.c/plaffine.c', 'PLplot/src/plcvt.c/plcvt.c', 'PLplot/src/plline.c/plline.c', 
# 'PLplot/src/plbox.c/plbox.c', 'PLplot/src/pltime.c/pltime.c', 'PLplot/src/plgridd.c/plgridd.c', 'PLplot/src/plgradient.c/plgradient.c', 'PLplot/src/plfill.c/plfill.c', 
# 'PLplot/src/plfreetype.c/plfreetype.c', 'PLplot/src/plot3d.c/plot3d.c', 'PLplot/src/plctrl.c/plctrl.c', 'PLplot/src/plcore.c/plcore.c', 'PLplot/src/mt19937ar.c/mt19937ar.c', 
# 'PLplot/src/plsdef.c/plsdef.c', 'PLplot/src/plbuf.c/plbuf.c', 'PLplot/src/plpage.c/plpage.c', 'PLplot/src/plhist.c/plhist.c', 'PLplot/src/pllegend.c/pllegend.c', 
# 'PLplot/src/plmetafile.c/plmetafile.c', 'PLplot/src/plmap.c/plmap.c',
# 'PLplot/src/plcont.c/plcont.c', 'PLplot/src/plvpor.c/plvpor.c', 'PLplot/src/plmem.c/plmem.c', 'PLplot/src/plsym.c/plsym.c', 'PLplot/src/plargs.c/plargs.c', 
# 'PLplot/src/plshade.c/plshade.c', 'PLplot/src/pltick.c/pltick.c', 'PLplot/src/plstripc.c/plstripc.c', 'PLplot/src/plwind.c/plwind.c', 'PLplot/src/plimage.c/plimage.c', 
# 'PLplot/src/plvect.c/plvect.c', 'PLplot/src/plarc.c/plarc.c', 'PLplot/src/plaffine.c/plaffine.c', 'PLplot/src/plcvt.c/plcvt.c', 'PLplot/src/plline.c/plline.c', 
# 'PLplot/src/plbox.c/plbox.c', 'PLplot/src/pltime.c/pltime.c', 'PLplot/src/plgridd.c/plgridd.c', 'PLplot/src/plgradient.c/plgradient.c', 'PLplot/src/plfill.c/plfill.c']

# FILES_TO_RUN = ['dealii/cmake/scripts/expand_instantiations.cc/expand_instantiations.cc',
#  'dealii/bundled/boost-1.62.0/libs/serialization/src/xml_iarchive.cpp/xml_iarchive.cpp',
#  'dealii/bundled/boost-1.62.0/libs/serialization/src/codecvt_null.cpp/codecvt_null.cpp',
#  'dealii/bundled/boost-1.62.0/libs/serialization/src/xml_grammar.cpp/xml_grammar.cpp',
#  'dealii/bundled/boost-1.62.0/libs/serialization/src/basic_text_iprimitive.cpp/basic_text_iprimitive.cpp',
#  'dealii/bundled/boost-1.62.0/libs/serialization/src/basic_pointer_iserializer.cpp/basic_pointer_iserializer.cpp',
#  'dealii/bundled/boost-1.62.0/libs/serialization/src/text_woarchive.cpp/text_woarchive.cpp',
#  'dealii/bundled/boost-1.62.0/libs/serialization/src/xml_archive_exception.cpp/xml_archive_exception.cpp',
#  'dealii/bundled/boost-1.62.0/libs/serialization/src/void_cast.cpp/void_cast.cpp',
#  'dealii/bundled/boost-1.62.0/libs/serialization/src/basic_iserializer.cpp/basic_iserializer.cpp',
#  'dealii/bundled/boost-1.62.0/libs/serialization/src/xml_wiarchive.cpp/xml_wiarchive.cpp',
#  'dealii/bundled/boost-1.62.0/libs/serialization/src/basic_pointer_oserializer.cpp/basic_pointer_oserializer.cpp',
#  'dealii/bundled/boost-1.62.0/libs/serialization/src/xml_wgrammar.cpp/xml_wgrammar.cpp',
#  'dealii/bundled/boost-1.62.0/libs/serialization/src/binary_iarchive.cpp/binary_iarchive.cpp',
#  'dealii/bundled/boost-1.62.0/libs/serialization/src/basic_text_woprimitive.cpp/basic_text_woprimitive.cpp',
#  'dealii/bundled/boost-1.62.0/libs/serialization/src/binary_woarchive.cpp/binary_woarchive.cpp',
#  'dealii/bundled/boost-1.62.0/libs/serialization/src/archive_exception.cpp/archive_exception.cpp',
#  'dealii/bundled/boost-1.62.0/libs/serialization/src/text_iarchive.cpp/text_iarchive.cpp',
#  'dealii/bundled/boost-1.62.0/libs/serialization/src/singleton.cpp/singleton.cpp',
#  'dealii/bundled/boost-1.62.0/libs/serialization/src/xml_woarchive.cpp/xml_woarchive.cpp',
#  'dealii/bundled/boost-1.62.0/libs/serialization/src/polymorphic_iarchive.cpp/polymorphic_iarchive.cpp',
#  'dealii/bundled/boost-1.62.0/libs/serialization/src/polymorphic_oarchive.cpp/polymorphic_oarchive.cpp',
#  'dealii/bundled/boost-1.62.0/libs/serialization/src/extended_type_info_typeid.cpp/extended_type_info_typeid.cpp',
#  'dealii/bundled/boost-1.62.0/libs/serialization/src/basic_archive.cpp/basic_archive.cpp',
#  'dealii/bundled/boost-1.62.0/libs/serialization/src/xml_oarchive.cpp/xml_oarchive.cpp',
#  'dealii/bundled/boost-1.62.0/libs/serialization/src/basic_serializer_map.cpp/basic_serializer_map.cpp',
#  'dealii/bundled/boost-1.62.0/libs/serialization/src/basic_iarchive.cpp/basic_iarchive.cpp',
#  'dealii/bundled/boost-1.62.0/libs/serialization/src/basic_xml_archive.cpp/basic_xml_archive.cpp',
#  'dealii/bundled/boost-1.62.0/libs/serialization/src/basic_oarchive.cpp/basic_oarchive.cpp',
#  'dealii/bundled/boost-1.62.0/libs/serialization/src/stl_port.cpp/stl_port.cpp',
#  'dealii/bundled/boost-1.62.0/libs/serialization/src/basic_oserializer.cpp/basic_oserializer.cpp',
#  'dealii/bundled/boost-1.62.0/libs/serialization/src/utf8_codecvt_facet.cpp/utf8_codecvt_facet.cpp',
#  'dealii/bundled/boost-1.62.0/libs/serialization/src/extended_type_info_no_rtti.cpp/extended_type_info_no_rtti.cpp',
#  'dealii/bundled/boost-1.62.0/libs/serialization/src/basic_text_oprimitive.cpp/basic_text_oprimitive.cpp',
#  'dealii/bundled/boost-1.62.0/libs/serialization/src/text_oarchive.cpp/text_oarchive.cpp',
#  'dealii/bundled/boost-1.62.0/libs/serialization/src/basic_text_wiprimitive.cpp/basic_text_wiprimitive.cpp',
#  'dealii/bundled/boost-1.62.0/libs/serialization/src/text_wiarchive.cpp/text_wiarchive.cpp',
#  'dealii/bundled/boost-1.62.0/libs/serialization/src/binary_wiarchive.cpp/binary_wiarchive.cpp',
#  'dealii/bundled/boost-1.62.0/libs/serialization/src/extended_type_info.cpp/extended_type_info.cpp',
#  'dealii/bundled/boost-1.62.0/libs/serialization/src/binary_oarchive.cpp/binary_oarchive.cpp',
#  'dealii/bundled/boost-1.62.0/libs/system/src/error_code.cpp/error_code.cpp',
#  'dealii/bundled/boost-1.62.0/libs/iostreams/src/file_descriptor.cpp/file_descriptor.cpp',
#  'dealii/bundled/boost-1.62.0/libs/iostreams/src/mapped_file.cpp/mapped_file.cpp',
#  'dealii/bundled/boost-1.62.0/libs/iostreams/src/gzip.cpp/gzip.cpp',
#  'dealii/bundled/boost-1.62.0/libs/iostreams/src/zlib.cpp/zlib.cpp',
#  'dealii/bundled/muparser_v2_2_4/src/muParserBase.cpp/muParserBase.cpp',
#  'dealii/bundled/muparser_v2_2_4/src/muParserCallback.cpp/muParserCallback.cpp',
#  'dealii/bundled/muparser_v2_2_4/src/muParserBytecode.cpp/muParserBytecode.cpp',
#  'dealii/bundled/muparser_v2_2_4/src/muParserTokenReader.cpp/muParserTokenReader.cpp',
#  'dealii/bundled/muparser_v2_2_4/src/muParser.cpp/muParser.cpp',
#  'dealii/bundled/muparser_v2_2_4/src/muParserInt.cpp/muParserInt.cpp',
#  'dealii/bundled/muparser_v2_2_4/src/muParserTest.cpp/muParserTest.cpp',
#  'dealii/bundled/muparser_v2_2_4/src/muParserError.cpp/muParserError.cpp',
#  'dealii/source/fe/fe_p1nc.cc/fe_p1nc.cc',
#  'dealii/source/fe/fe_dgp_monomial.cc/fe_dgp_monomial.cc',
#  'dealii/source/fe/fe_values_inst6.cc/fe_values_inst6.cc',
#  'dealii/source/fe/fe_q_hierarchical.cc/fe_q_hierarchical.cc',
#  'dealii/source/fe/fe_rt_bubbles.cc/fe_rt_bubbles.cc',
#  'dealii/source/fe/fe_dgp.cc/fe_dgp.cc',
#  'dealii/source/fe/mapping_q1_eulerian.cc/mapping_q1_eulerian.cc',
#  'dealii/source/fe/mapping_q_generic.cc/mapping_q_generic.cc',
#  'dealii/source/fe/fe_q_base.cc/fe_q_base.cc',
#  'dealii/source/fe/fe_data.cc/fe_data.cc',
#  'dealii/source/fe/fe_bernardi_raugel.cc/fe_bernardi_raugel.cc',
#  'dealii/source/fe/fe_nedelec_sz.cc/fe_nedelec_sz.cc',
#  'dealii/source/fe/fe_poly.cc/fe_poly.cc',
#  'dealii/source/fe/fe_series_fourier.cc/fe_series_fourier.cc',
#  'dealii/source/fe/fe_tools.cc/fe_tools.cc',
#  'dealii/source/fe/fe_raviart_thomas_nodal.cc/fe_raviart_thomas_nodal.cc',
#  'dealii/source/fe/fe_system.cc/fe_system.cc',
#  'dealii/source/fe/mapping.cc/mapping.cc',
#  'dealii/source/fe/fe_values_inst2.cc/fe_values_inst2.cc',
#  'dealii/source/fe/fe_enriched.cc/fe_enriched.cc',
#  'dealii/source/fe/mapping_q1.cc/mapping_q1.cc',
#  'dealii/source/fe/fe_q_iso_q1.cc/fe_q_iso_q1.cc',
#  'dealii/source/fe/fe_nedelec.cc/fe_nedelec.cc',
#  'dealii/source/fe/fe_abf.cc/fe_abf.cc',
#  'dealii/source/fe/fe_bernstein.cc/fe_bernstein.cc',
#  'dealii/source/fe/fe_rannacher_turek.cc/fe_rannacher_turek.cc',
#  'dealii/source/fe/mapping_q_eulerian.cc/mapping_q_eulerian.cc',
#  'dealii/source/fe/fe_dgq.cc/fe_dgq.cc',
#  'dealii/source/fe/fe_series_legendre.cc/fe_series_legendre.cc',
#  'dealii/source/fe/block_mask.cc/block_mask.cc',
#  'dealii/source/fe/fe_values_inst4.cc/fe_values_inst4.cc',
#  'dealii/source/fe/component_mask.cc/component_mask.cc',
#  'dealii/source/fe/fe_values_inst5.cc/fe_values_inst5.cc',
#  'dealii/source/fe/fe_poly_tensor.cc/fe_poly_tensor.cc',
#  'dealii/source/fe/fe_bdm.cc/fe_bdm.cc',
#  'dealii/source/fe/fe_q_bubbles.cc/fe_q_bubbles.cc',
#  'dealii/source/fe/mapping_c1.cc/mapping_c1.cc',
#  'dealii/source/fe/mapping_manifold.cc/mapping_manifold.cc',
#  'dealii/source/fe/fe_q_dg0.cc/fe_q_dg0.cc',
#  'dealii/source/fe/mapping_q.cc/mapping_q.cc',
#  'dealii/source/fe/fe_q.cc/fe_q.cc',
#  'dealii/source/fe/fe_values.cc/fe_values.cc',
#  'dealii/source/fe/fe_dgp_nonparametric.cc/fe_dgp_nonparametric.cc',
#  'dealii/source/fe/fe_values_extractors.cc/fe_values_extractors.cc',
#  'dealii/source/fe/fe_dg_vector.cc/fe_dg_vector.cc',
#  'dealii/source/fe/fe_series.cc/fe_series.cc',
#  'dealii/source/fe/fe_tools_extrapolate.cc/fe_tools_extrapolate.cc',
#  'dealii/source/fe/fe_face.cc/fe_face.cc',
#  'dealii/source/fe/fe_nothing.cc/fe_nothing.cc',
#  'dealii/source/fe/mapping_fe_field.cc/mapping_fe_field.cc',
#  'dealii/source/fe/fe_tools_interpolate.cc/fe_tools_interpolate.cc',
#  'dealii/source/fe/mapping_cartesian.cc/mapping_cartesian.cc',
#  'dealii/source/fe/fe_raviart_thomas.cc/fe_raviart_thomas.cc',
#  'dealii/source/fe/fe.cc/fe.cc',
#  'dealii/source/fe/fe_values_inst3.cc/fe_values_inst3.cc',
#  'dealii/source/fe/mapping_fe_field_inst2.cc/mapping_fe_field_inst2.cc',
#  'dealii/source/fe/fe_trace.cc/fe_trace.cc',
#  'dealii/source/dofs/dof_handler_policy.cc/dof_handler_policy.cc',
#  'dealii/source/dofs/block_info.cc/block_info.cc',
#  'dealii/source/dofs/number_cache.cc/number_cache.cc',
#  'dealii/source/dofs/dof_accessor_set.cc/dof_accessor_set.cc',
#  'dealii/source/dofs/dof_handler.cc/dof_handler.cc',
#  'dealii/source/dofs/dof_objects.cc/dof_objects.cc',
#  'dealii/source/dofs/dof_tools.cc/dof_tools.cc',
#  'dealii/source/dofs/dof_accessor.cc/dof_accessor.cc',
#  'dealii/source/dofs/dof_tools_sparsity.cc/dof_tools_sparsity.cc',
#  'dealii/source/dofs/dof_accessor_get.cc/dof_accessor_get.cc',
#  'dealii/source/dofs/dof_faces.cc/dof_faces.cc',
#  'dealii/source/dofs/dof_renumbering.cc/dof_renumbering.cc',
#  'dealii/source/dofs/dof_tools_constraints.cc/dof_tools_constraints.cc',
#  'dealii/source/numerics/solution_transfer_inst4.cc/solution_transfer_inst4.cc',
#  'dealii/source/numerics/matrix_creator_inst2.cc/matrix_creator_inst2.cc',
#  'dealii/source/numerics/vector_tools_project_hp.cc/vector_tools_project_hp.cc',
#  'dealii/source/numerics/histogram.cc/histogram.cc',
#  'dealii/source/numerics/data_out_stack.cc/data_out_stack.cc',
#  'dealii/source/numerics/vector_tools_project_inst3.cc/vector_tools_project_inst3.cc',
#  'dealii/source/numerics/error_estimator_1d.cc/error_estimator_1d.cc',
#  'dealii/source/numerics/vector_tools_interpolate.cc/vector_tools_interpolate.cc',
#  'dealii/source/numerics/vector_tools_project_qp.cc/vector_tools_project_qp.cc',
#  'dealii/source/numerics/dof_output_operator.cc/dof_output_operator.cc',
#  'dealii/source/numerics/matrix_tools.cc/matrix_tools.cc',
#  'dealii/source/numerics/error_estimator.cc/error_estimator.cc',
#  'dealii/source/numerics/vector_tools_mean_value.cc/vector_tools_mean_value.cc',
#  'dealii/source/numerics/vector_tools_integrate_difference.cc/vector_tools_integrate_difference.cc',
#  'dealii/source/numerics/data_out_rotation.cc/data_out_rotation.cc',
#  'dealii/source/numerics/solution_transfer.cc/solution_transfer.cc',
#  'dealii/source/numerics/data_out_dof_data.cc/data_out_dof_data.cc',
#  'dealii/source/numerics/fe_field_function.cc/fe_field_function.cc',
#  'dealii/source/numerics/data_out_dof_data_inst2.cc/data_out_dof_data_inst2.cc',
#  'dealii/source/numerics/solution_transfer_inst3.cc/solution_transfer_inst3.cc',
#  'dealii/source/numerics/matrix_creator.cc/matrix_creator.cc',
#  'dealii/source/numerics/data_postprocessor.cc/data_postprocessor.cc',
#  'dealii/source/numerics/vector_tools_rhs.cc/vector_tools_rhs.cc',
#  'dealii/source/numerics/data_out_faces.cc/data_out_faces.cc',
#  'dealii/source/numerics/vector_tools_boundary.cc/vector_tools_boundary.cc',
#  'dealii/source/numerics/point_value_history.cc/point_value_history.cc',
#  'dealii/source/numerics/vector_tools_project.cc/vector_tools_project.cc',
#  'dealii/source/numerics/matrix_creator_inst3.cc/matrix_creator_inst3.cc',
#  'dealii/source/numerics/kdtree.cc/kdtree.cc',
#  'dealii/source/numerics/vector_tools_constraints.cc/vector_tools_constraints.cc',
#  'dealii/source/numerics/vector_tools_point_value.cc/vector_tools_point_value.cc',
#  'dealii/source/numerics/vector_tools_project_codim.cc/vector_tools_project_codim.cc',
#  'dealii/source/numerics/matrix_tools_once.cc/matrix_tools_once.cc',
#  'dealii/source/numerics/vector_tools_project_qpmf.cc/vector_tools_project_qpmf.cc',
#  'dealii/source/numerics/data_out.cc/data_out.cc',
#  'dealii/source/numerics/time_dependent.cc/time_dependent.cc',
#  'dealii/source/numerics/error_estimator_inst2.cc/error_estimator_inst2.cc',
#  'dealii/source/numerics/derivative_approximation.cc/derivative_approximation.cc',
#  'dealii/source/numerics/data_out_dof_data_codim.cc/data_out_dof_data_codim.cc',
#  'dealii/source/numerics/solution_transfer_inst2.cc/solution_transfer_inst2.cc',
#  'dealii/source/numerics/vector_tools_point_gradient.cc/vector_tools_point_gradient.cc',
#  'dealii/source/numerics/vector_tools_project_inst2.cc/vector_tools_project_inst2.cc',
#  'dealii/source/sundials/ida.cc/ida.cc',
#  'dealii/source/sundials/copy.cc/copy.cc',
#  'dealii/source/sundials/arkode.cc/arkode.cc',
#  'dealii/source/sundials/kinsol.cc/kinsol.cc',
#  'dealii/source/lac/block_vector.cc/block_vector.cc',
#  'dealii/source/lac/affine_constraints.cc/affine_constraints.cc',
#  'dealii/source/lac/block_sparse_matrix_ez.cc/block_sparse_matrix_ez.cc',
#  'dealii/source/lac/block_sparsity_pattern.cc/block_sparsity_pattern.cc',
#  'dealii/source/lac/block_matrix_array.cc/block_matrix_array.cc',
#  'dealii/source/lac/block_sparse_matrix.cc/block_sparse_matrix.cc']

# FILES_TO_RUN = ['curl/tests/server/testpart.c/testpart.c', 'curl/tests/server/util.c/util.c', 'curl/tests/server/sws.c/sws.c', 'curl/tests/server/getpart.c/getpart.c', 'curl/tests/server/disabled.c/disabled.c', 'curl/tests/server/rtspd.c/rtspd.c', 'curl/tests/server/tftpd.c/tftpd.c', 'curl/tests/server/fake_ntlm.c/fake_ntlm.c', 'curl/tests/server/sockfilt.c/sockfilt.c', 'curl/tests/libtest/lib537.c/lib537.c', 'curl/tests/libtest/lib554.c/lib554.c', 'curl/tests/libtest/lib599.c/lib599.c', 'curl/tests/libtest/lib1512.c/lib1512.c', 'curl/tests/libtest/lib567.c/lib567.c', 'curl/tests/libtest/lib1156.c/lib1156.c', 'curl/tests/libtest/lib659.c/lib659.c', 'curl/tests/libtest/lib574.c/lib574.c', 'curl/tests/libtest/lib553.c/lib553.c', 'curl/tests/libtest/lib541.c/lib541.c', 'curl/tests/libtest/lib1514.c/lib1514.c', 'curl/tests/libtest/first.c/first.c', 'curl/tests/libtest/chkdecimalpoint.c/chkdecimalpoint.c', 'curl/tests/libtest/lib1537.c/lib1537.c', 'curl/tests/libtest/lib1536.c/lib1536.c', 'curl/tests/libtest/lib598.c/lib598.c', 'curl/tests/libtest/lib559.c/lib559.c', 'curl/tests/libtest/lib1506.c/lib1506.c', 'curl/tests/libtest/lib1509.c/lib1509.c', 'curl/tests/libtest/lib1538.c/lib1538.c', 'curl/tests/libtest/libntlmconnect.c/libntlmconnect.c', 'curl/tests/libtest/lib558.c/lib558.c', 'curl/tests/libtest/lib523.c/lib523.c', 'curl/tests/libtest/lib1550.c/lib1550.c', 'curl/tests/libtest/lib1556.c/lib1556.c', 'curl/tests/libtest/lib525.c/lib525.c', 'curl/tests/libtest/lib1564.c/lib1564.c', 'curl/tests/libtest/lib1526.c/lib1526.c', 'curl/tests/libtest/lib1520.c/lib1520.c', 'curl/tests/libtest/lib549.c/lib549.c', 'curl/tests/libtest/lib1511.c/lib1511.c', 'curl/tests/libtest/sethostname.c/sethostname.c', 'curl/tests/libtest/lib539.c/lib539.c', 'curl/tests/libtest/lib568.c/lib568.c', 'curl/tests/libtest/lib583.c/lib583.c', 'curl/tests/libtest/lib543.c/lib543.c', 'curl/tests/libtest/lib654.c/lib654.c', 'curl/tests/libtest/lib575.c/lib575.c', 'curl/tests/libtest/lib1554.c/lib1554.c', 'curl/tests/libtest/lib513.c/lib513.c', 'curl/tests/libtest/lib1533.c/lib1533.c', 'curl/tests/libtest/lib547.c/lib547.c', 'curl/tests/libtest/lib1541.c/lib1541.c', 'curl/tests/libtest/lib643.c/lib643.c', 'curl/tests/libtest/lib582.c/lib582.c',
# 'curl/tests/libtest/lib582.c/lib582.c', 'curl/src/tool_getparam.c/tool_getparam.c', 'curl/src/tool_metalink.c/tool_metalink.c', 'curl/src/tool_homedir.c/tool_homedir.c', 'curl/src/tool_cb_prg.c/tool_cb_prg.c', 'curl/src/tool_bname.c/tool_bname.c', 'curl/src/tool_help.c/tool_help.c', 'curl/src/tool_cb_hdr.c/tool_cb_hdr.c', 'curl/src/tool_operhlp.c/tool_operhlp.c', 'curl/lib/imap.c/imap.c', 'curl/lib/hostcheck.c/hostcheck.c', 'curl/lib/ftplistparser.c/ftplistparser.c', 'curl/lib/vauth/digest.c/digest.c', 'curl/lib/vauth/vauth.c/vauth.c', 'curl/lib/vauth/digest_sspi.c/digest_sspi.c', 'curl/lib/vauth/ntlm_sspi.c/ntlm_sspi.c', 'curl/lib/vauth/cram.c/cram.c', 'curl/lib/vauth/spnego_sspi.c/spnego_sspi.c', 'curl/lib/vauth/krb5_sspi.c/krb5_sspi.c', 'curl/lib/vauth/oauth2.c/oauth2.c', 'curl/lib/vauth/cleartext.c/cleartext.c', 'curl/lib/vauth/spnego_gssapi.c/spnego_gssapi.c', 'curl/lib/curl_memrchr.c/curl_memrchr.c', 'curl/lib/curl_path.c/curl_path.c',
# 'curl/lib/imap.c/imap.c', 'curl/lib/hostcheck.c/hostcheck.c', 'curl/lib/ftplistparser.c/ftplistparser.c', 'curl/lib/vauth/digest.c/digest.c', 'curl/lib/vauth/vauth.c/vauth.c', 'curl/lib/vauth/digest_sspi.c/digest_sspi.c', 'curl/lib/vauth/ntlm_sspi.c/ntlm_sspi.c', 'curl/lib/vauth/cram.c/cram.c', 'curl/lib/vauth/spnego_sspi.c/spnego_sspi.c', 'curl/lib/vauth/krb5_sspi.c/krb5_sspi.c', 'curl/lib/vauth/oauth2.c/oauth2.c', 'curl/lib/vauth/cleartext.c/cleartext.c', 'curl/lib/vauth/spnego_gssapi.c/spnego_gssapi.c', 'curl/lib/curl_memrchr.c/curl_memrchr.c', 'curl/lib/curl_path.c/curl_path.c', 'curl/lib/security.c/security.c', 'curl/lib/hostasyn.c/hostasyn.c', 'curl/lib/http2.c/http2.c', 'curl/lib/strdup.c/strdup.c', 'curl/lib/asyn-thread.c/asyn-thread.c', 'curl/lib/transfer.c/transfer.c', 'curl/lib/content_encoding.c/content_encoding.c', 'curl/lib/timeval.c/timeval.c', 'curl/lib/dict.c/dict.c', 'curl/lib/socks_gssapi.c/socks_gssapi.c', 'curl/lib/doh.c/doh.c', 'curl/lib/rtsp.c/rtsp.c', 'curl/lib/gopher.c/gopher.c', 'curl/lib/curl_sasl.c/curl_sasl.c', 'curl/lib/x509asn1.c/x509asn1.c', 'curl/lib/file.c/file.c', 'curl/lib/formdata.c/formdata.c', 'curl/lib/tftp.c/tftp.c', 'curl/lib/mime.c/mime.c', 'curl/lib/http.c/http.c', 'curl/lib/hostsyn.c/hostsyn.c', 'curl/lib/openldap.c/openldap.c', 'curl/lib/select.c/select.c', 'curl/lib/http_chunks.c/http_chunks.c', 'curl/lib/splay.c/splay.c', 'curl/lib/curl_fnmatch.c/curl_fnmatch.c', 'curl/lib/vquic/ngtcp2.c/ngtcp2.c', 'curl/lib/asyn-ares.c/asyn-ares.c', 'curl/lib/escape.c/escape.c',
# 'curl/tests/server/sockfilt.c/sockfilt.c', 'curl/tests/libtest/lib537.c/lib537.c', 'curl/tests/libtest/lib554.c/lib554.c', 'curl/tests/libtest/lib599.c/lib599.c', 'curl/tests/libtest/lib1512.c/lib1512.c', 'curl/tests/libtest/lib567.c/lib567.c', 'curl/tests/libtest/lib1156.c/lib1156.c', 'curl/tests/libtest/lib659.c/lib659.c', 'curl/tests/libtest/lib574.c/lib574.c', 'curl/tests/libtest/lib553.c/lib553.c', 'curl/tests/libtest/lib541.c/lib541.c', 'curl/tests/libtest/lib1514.c/lib1514.c', 'curl/tests/libtest/first.c/first.c', 'curl/tests/libtest/chkdecimalpoint.c/chkdecimalpoint.c', 'curl/tests/libtest/lib1537.c/lib1537.c', 'curl/tests/libtest/lib1536.c/lib1536.c', 'curl/tests/libtest/lib598.c/lib598.c', 'curl/tests/libtest/lib559.c/lib559.c', 'curl/tests/libtest/lib1506.c/lib1506.c', 'curl/tests/libtest/lib1509.c/lib1509.c', 'curl/tests/libtest/lib1538.c/lib1538.c', 'curl/tests/libtest/libntlmconnect.c/libntlmconnect.c', 'curl/tests/libtest/lib558.c/lib558.c', 'curl/tests/libtest/lib523.c/lib523.c', 'curl/tests/libtest/lib1550.c/lib1550.c', 'curl/tests/libtest/lib1556.c/lib1556.c', 'curl/tests/libtest/lib525.c/lib525.c', 'curl/tests/libtest/lib1564.c/lib1564.c', 'curl/tests/libtest/lib1526.c/lib1526.c', 'curl/tests/libtest/lib1520.c/lib1520.c', 'curl/tests/libtest/lib549.c/lib549.c', 'curl/tests/libtest/lib1511.c/lib1511.c', 'curl/tests/libtest/sethostname.c/sethostname.c', 'curl/tests/libtest/lib539.c/lib539.c', 'curl/tests/libtest/lib568.c/lib568.c', 'curl/tests/libtest/lib583.c/lib583.c', 'curl/tests/libtest/lib543.c/lib543.c', 'curl/tests/libtest/lib654.c/lib654.c', 'curl/tests/libtest/lib575.c/lib575.c', 'curl/tests/libtest/lib1554.c/lib1554.c', 'curl/tests/libtest/lib513.c/lib513.c', 'curl/tests/libtest/lib1533.c/lib1533.c', 'curl/tests/libtest/lib547.c/lib547.c', 'curl/tests/libtest/lib1541.c/lib1541.c', 'curl/tests/libtest/lib643.c/lib643.c', 'curl/tests/libtest/lib582.c/lib582.c']

# FILES_TO_RUN = [
#  'contrib/visupng/VisualPng.c',
#  'contrib/visupng/PngFile.c',
#  'contrib/gregbook/rpng-x.c',
#  'contrib/gregbook/readpng.c',
#  'contrib/gregbook/rpng2-x.c',
#  'contrib/gregbook/wpng.c',
#  'contrib/powerpc-vsx/linux.c',
#  'contrib/powerpc-vsx/linux_aux.c',
#  'contrib/tools/pngcp.c',
#  'contrib/tools/pngfix.c',
#  'contrib/tools/png-fix-itxt.c',
#  'contrib/libtests/pngstest.c',
#  'contrib/libtests/pngunknown.c',
#  'contrib/libtests/pngimage.c',
#  'contrib/libtests/pngvalid.c',
#  'intel/filter_sse2_intrinsics.c',
#  'intel/intel_init.c']

#FILES_TO_RUN = ['SFML/src/SFML/System/MemoryInputStream.cpp/MemoryInputStream.cpp', 'SFML/src/SFML/System/ThreadLocal.cpp/ThreadLocal.cpp', 'SFML/src/SFML/System/FileInputStream.cpp/FileInputStream.cpp', 'SFML/src/SFML/System/Time.cpp/Time.cpp', 'SFML/src/SFML/System/Unix/ThreadImpl.cpp/ThreadImpl.cpp', 'SFML/src/SFML/System/Unix/MutexImpl.cpp/MutexImpl.cpp', 'SFML/src/SFML/System/Unix/SleepImpl.cpp/SleepImpl.cpp', 'SFML/src/SFML/System/Unix/ThreadLocalImpl.cpp/ThreadLocalImpl.cpp', 'SFML/src/SFML/System/Unix/ClockImpl.cpp/ClockImpl.cpp', 'SFML/src/SFML/System/Thread.cpp/Thread.cpp', 'SFML/src/SFML/System/Clock.cpp/Clock.cpp', 'SFML/src/SFML/System/Mutex.cpp/Mutex.cpp', 'SFML/src/SFML/System/Err.cpp/Err.cpp', 'SFML/src/SFML/System/Lock.cpp/Lock.cpp', 'SFML/src/SFML/System/String.cpp/String.cpp', 'SFML/src/SFML/System/Sleep.cpp/Sleep.cpp', 'SFML/src/SFML/Network/TcpSocket.cpp/TcpSocket.cpp', 'SFML/src/SFML/Network/SocketSelector.cpp/SocketSelector.cpp', 'SFML/src/SFML/Network/TcpListener.cpp/TcpListener.cpp', 'SFML/src/SFML/Network/Packet.cpp/Packet.cpp', 'SFML/src/SFML/Network/Unix/SocketImpl.cpp/SocketImpl.cpp', 'SFML/src/SFML/Network/UdpSocket.cpp/UdpSocket.cpp', 'SFML/src/SFML/Network/Socket.cpp/Socket.cpp', 'SFML/src/SFML/Network/Http.cpp/Http.cpp', 'SFML/src/SFML/Network/IpAddress.cpp/IpAddress.cpp', 'SFML/src/SFML/Network/Ftp.cpp/Ftp.cpp', 'SFML/src/SFML/Graphics/RenderTextureImplFBO.cpp/RenderTextureImplFBO.cpp', 'SFML/src/SFML/Graphics/RenderTexture.cpp/RenderTexture.cpp', 'SFML/src/SFML/Graphics/Glsl.cpp/Glsl.cpp', 'SFML/src/SFML/Graphics/Transform.cpp/Transform.cpp', 'SFML/src/SFML/Graphics/GLCheck.cpp/GLCheck.cpp', 'SFML/src/SFML/Graphics/Color.cpp/Color.cpp', 'SFML/src/SFML/Graphics/VertexBuffer.cpp/VertexBuffer.cpp', 'SFML/src/SFML/Graphics/View.cpp/View.cpp', 'SFML/src/SFML/Graphics/TextureSaver.cpp/TextureSaver.cpp', 'SFML/src/SFML/Graphics/VertexArray.cpp/VertexArray.cpp', 'SFML/src/SFML/Graphics/Image.cpp/Image.cpp', 'SFML/src/SFML/Graphics/CircleShape.cpp/CircleShape.cpp', 'SFML/src/SFML/Graphics/RenderWindow.cpp/RenderWindow.cpp', 'SFML/src/SFML/Graphics/RectangleShape.cpp/RectangleShape.cpp', 'SFML/src/SFML/Graphics/Texture.cpp/Texture.cpp', 'SFML/src/SFML/Graphics/GLExtensions.cpp/GLExtensions.cpp', 'SFML/src/SFML/Graphics/Font.cpp/Font.cpp', 'SFML/src/SFML/Graphics/BlendMode.cpp/BlendMode.cpp', 'SFML/src/SFML/Graphics/RenderTextureImpl.cpp/RenderTextureImpl.cpp', 'SFML/src/SFML/Graphics/Transformable.cpp/Transformable.cpp', 'SFML/src/SFML/Graphics/ImageLoader.cpp/ImageLoader.cpp', 'SFML/src/SFML/Graphics/ConvexShape.cpp/ConvexShape.cpp', 'SFML/src/SFML/Graphics/Text.cpp/Text.cpp', 'SFML/src/SFML/Graphics/Shape.cpp/Shape.cpp', 'SFML/src/SFML/Graphics/RenderTextureImplDefault.cpp/RenderTextureImplDefault.cpp', 'SFML/src/SFML/Graphics/RenderTarget.cpp/RenderTarget.cpp', 'SFML/src/SFML/Graphics/Shader.cpp/Shader.cpp', 'SFML/src/SFML/Graphics/RenderStates.cpp/RenderStates.cpp', 'SFML/src/SFML/Graphics/Vertex.cpp/Vertex.cpp', 'SFML/src/SFML/Graphics/Sprite.cpp/Sprite.cpp', 'SFML/src/SFML/Audio/SoundFileReaderWav.cpp/SoundFileReaderWav.cpp', 'SFML/src/SFML/Audio/ALCheck.cpp/ALCheck.cpp', 'SFML/src/SFML/Audio/AudioDevice.cpp/AudioDevice.cpp', 'SFML/src/SFML/Audio/SoundFileWriterFlac.cpp/SoundFileWriterFlac.cpp', 'SFML/src/SFML/Audio/SoundFileWriterWav.cpp/SoundFileWriterWav.cpp', 'SFML/src/SFML/Audio/Sound.cpp/Sound.cpp', 'SFML/src/SFML/Audio/SoundRecorder.cpp/SoundRecorder.cpp', 'SFML/src/SFML/Audio/SoundFileWriterOgg.cpp/SoundFileWriterOgg.cpp', 'SFML/src/SFML/Audio/InputSoundFile.cpp/InputSoundFile.cpp', 'SFML/src/SFML/Audio/OutputSoundFile.cpp/OutputSoundFile.cpp', 'SFML/src/SFML/Audio/Listener.cpp/Listener.cpp', 'SFML/src/SFML/Audio/SoundFileReaderFlac.cpp/SoundFileReaderFlac.cpp', 'SFML/src/SFML/Audio/SoundBuffer.cpp/SoundBuffer.cpp', 'SFML/src/SFML/Audio/SoundBufferRecorder.cpp/SoundBufferRecorder.cpp', 'SFML/src/SFML/Audio/AlResource.cpp/AlResource.cpp', 'SFML/src/SFML/Audio/SoundFileReaderOgg.cpp/SoundFileReaderOgg.cpp', 'SFML/src/SFML/Audio/SoundSource.cpp/SoundSource.cpp', 'SFML/src/SFML/Audio/Music.cpp/Music.cpp', 'SFML/src/SFML/Audio/SoundFileFactory.cpp/SoundFileFactory.cpp', 'SFML/src/SFML/Audio/SoundStream.cpp/SoundStream.cpp', 'SFML/src/SFML/Window/Mouse.cpp/Mouse.cpp', 'SFML/src/SFML/Window/Window.cpp/Window.cpp', 'SFML/src/SFML/Window/Touch.cpp/Touch.cpp', 'SFML/src/SFML/Window/WindowBase.cpp/WindowBase.cpp', 'SFML/src/SFML/Window/Clipboard.cpp/Clipboard.cpp', 'SFML/src/SFML/Window/GlContext.cpp/GlContext.cpp', 'SFML/src/SFML/Window/Context.cpp/Context.cpp', 'SFML/src/SFML/Window/EglContext.cpp/EglContext.cpp', 'SFML/src/SFML/Window/Keyboard.cpp/Keyboard.cpp', 'SFML/src/SFML/Window/Vulkan.cpp/Vulkan.cpp', 'SFML/src/SFML/Window/GlResource.cpp/GlResource.cpp', 'SFML/src/SFML/Window/Unix/WindowImplX11.cpp/WindowImplX11.cpp', 'SFML/src/SFML/Window/Unix/ClipboardImpl.cpp/ClipboardImpl.cpp', 'SFML/src/SFML/Window/Unix/InputImpl.cpp/InputImpl.cpp', 'SFML/src/SFML/Window/Unix/GlxContext.cpp/GlxContext.cpp', 'SFML/src/SFML/Window/Unix/Display.cpp/Display.cpp', 'SFML/src/SFML/Window/Unix/CursorImpl.cpp/CursorImpl.cpp', 'SFML/src/SFML/Window/Unix/JoystickImpl.cpp/JoystickImpl.cpp', 'SFML/src/SFML/Window/Unix/VideoModeImpl.cpp/VideoModeImpl.cpp', 'SFML/src/SFML/Window/Unix/SensorImpl.cpp/SensorImpl.cpp', 'SFML/src/SFML/Window/Unix/VulkanImplX11.cpp/VulkanImplX11.cpp', 'SFML/src/SFML/Window/Cursor.cpp/Cursor.cpp', 'SFML/src/SFML/Window/Sensor.cpp/Sensor.cpp', 'SFML/src/SFML/Window/VideoMode.cpp/VideoMode.cpp', 'SFML/src/SFML/Window/EGLCheck.cpp/EGLCheck.cpp', 'SFML/src/SFML/Window/JoystickManager.cpp/JoystickManager.cpp', 'SFML/src/SFML/Window/Joystick.cpp/Joystick.cpp', 'SFML/src/SFML/Window/WindowImpl.cpp/WindowImpl.cpp', 'SFML/src/SFML/Window/SensorManager.cpp/SensorManager.cpp']

#FILES_TO_RUN = ['Stockfish-sf_11/src/search.cpp/search.cpp', 'Stockfish-sf_11/src/bitboard.cpp/bitboard.cpp', 'Stockfish-sf_11/src/ucioption.cpp/ucioption.cpp', 'Stockfish-sf_11/src/movegen.cpp/movegen.cpp', 'Stockfish-sf_11/src/bitbase.cpp/bitbase.cpp', 'Stockfish-sf_11/src/psqt.cpp/psqt.cpp', 'Stockfish-sf_11/src/misc.cpp/misc.cpp', 'Stockfish-sf_11/src/evaluate.cpp/evaluate.cpp', 'Stockfish-sf_11/src/material.cpp/material.cpp', 'Stockfish-sf_11/src/uci.cpp/uci.cpp', 'Stockfish-sf_11/src/timeman.cpp/timeman.cpp', 'Stockfish-sf_11/src/position.cpp/position.cpp', 'Stockfish-sf_11/src/thread.cpp/thread.cpp', 'Stockfish-sf_11/src/endgame.cpp/endgame.cpp', 'Stockfish-sf_11/src/benchmark.cpp/benchmark.cpp', 'Stockfish-sf_11/src/syzygy/tbprobe.cpp/tbprobe.cpp', 'Stockfish-sf_11/src/pawns.cpp/pawns.cpp', 'Stockfish-sf_11/src/main.cpp/main.cpp', 'Stockfish-sf_11/src/movepick.cpp/movepick.cpp', 'Stockfish-sf_11/src/tt.cpp/tt.cpp']

#FILES_TO_RUN = ['gromacs/src/external/tinyxml2/tinyxml2.cpp/tinyxml2.cpp', 'gromacs/src/external/googletest/googletest/src/gtest-all.cc/gtest-all.cc', 'gromacs/src/external/googletest/googletest/src/gtest_main.cc/gtest_main.cc', 'gromacs/src/external/googletest/googlemock/src/gmock-all.cc/gmock-all.cc', 'gromacs/src/external/thread_mpi/src/gather.cpp/gather.cpp', 'gromacs/src/external/thread_mpi/src/bcast.cpp/bcast.cpp', 'gromacs/src/external/thread_mpi/src/topology.cpp/topology.cpp', 'gromacs/src/external/thread_mpi/src/alltoall.cpp/alltoall.cpp', 'gromacs/src/external/thread_mpi/src/profile.cpp/profile.cpp', 'gromacs/src/external/thread_mpi/src/once.cpp/once.cpp', 'gromacs/src/external/thread_mpi/src/reduce.cpp/reduce.cpp', 'gromacs/src/external/thread_mpi/src/atomic.cpp/atomic.cpp', 'gromacs/src/external/thread_mpi/src/list.cpp/list.cpp', 'gromacs/src/external/thread_mpi/src/p2p_protocol.cpp/p2p_protocol.cpp', 'gromacs/src/external/thread_mpi/src/group.cpp/group.cpp', 'gromacs/src/external/thread_mpi/src/tmpi_malloc.cpp/tmpi_malloc.cpp', 'gromacs/src/external/thread_mpi/src/comm.cpp/comm.cpp', 'gromacs/src/external/thread_mpi/src/errhandler.cpp/errhandler.cpp', 'gromacs/src/external/thread_mpi/src/pthreads.cpp/pthreads.cpp', 'gromacs/src/external/thread_mpi/src/tmpi_init.cpp/tmpi_init.cpp', 'gromacs/src/external/thread_mpi/src/system_error.cpp/system_error.cpp', 'gromacs/src/external/thread_mpi/src/type.cpp/type.cpp', 'gromacs/src/external/thread_mpi/src/reduce_fast.cpp/reduce_fast.cpp', 'gromacs/src/external/thread_mpi/src/event.cpp/event.cpp', 'gromacs/src/external/thread_mpi/src/scatter.cpp/scatter.cpp', 'gromacs/src/external/thread_mpi/src/p2p_wait.cpp/p2p_wait.cpp', 'gromacs/src/external/thread_mpi/src/lock.cpp/lock.cpp', 'gromacs/src/external/thread_mpi/src/scan.cpp/scan.cpp', 'gromacs/src/external/thread_mpi/src/p2p_send_recv.cpp/p2p_send_recv.cpp', 'gromacs/src/external/thread_mpi/src/numa_malloc.cpp/numa_malloc.cpp', 'gromacs/src/external/thread_mpi/src/collective.cpp/collective.cpp', 'gromacs/src/external/thread_mpi/src/barrier.cpp/barrier.cpp', 'gromacs/src/testutils/tests/mpitest.cpp/mpitest.cpp', 'gromacs/src/testutils/tests/interactivetest.cpp/interactivetest.cpp', 'gromacs/src/testutils/tests/refdata_tests.cpp/refdata_tests.cpp', 'gromacs/src/testutils/tests/xvgtest_tests.cpp/xvgtest_tests.cpp', 'gromacs/src/testutils/tests/testasserts_tests.cpp/testasserts_tests.cpp', 'gromacs/src/testutils/mpitest.cpp/mpitest.cpp', 'gromacs/src/testutils/testoptions.cpp/testoptions.cpp', 'gromacs/src/testutils/stdiohelper.cpp/stdiohelper.cpp', 'gromacs/src/testutils/interactivetest.cpp/interactivetest.cpp', 'gromacs/src/testutils/stringtest.cpp/stringtest.cpp', 'gromacs/src/testutils/refdata_xml.cpp/refdata_xml.cpp', 'gromacs/src/testutils/tprfilegenerator.cpp/tprfilegenerator.cpp', 'gromacs/src/testutils/testfilemanager.cpp/testfilemanager.cpp', 'gromacs/src/testutils/testinit.cpp/testinit.cpp', 'gromacs/src/testutils/cmdlinetest.cpp/cmdlinetest.cpp', 'gromacs/src/testutils/textblockmatchers.cpp/textblockmatchers.cpp', 'gromacs/src/testutils/loggertest.cpp/loggertest.cpp', 'gromacs/src/testutils/testasserts.cpp/testasserts.cpp', 'gromacs/src/testutils/refdata.cpp/refdata.cpp', 'gromacs/src/testutils/mpi_printer.cpp/mpi_printer.cpp', 'gromacs/src/testutils/simulationdatabase.cpp/simulationdatabase.cpp', 'gromacs/src/testutils/conftest.cpp/conftest.cpp', 'gromacs/src/testutils/testmatchers.cpp/testmatchers.cpp', 'gromacs/src/testutils/unittest_main.cpp/unittest_main.cpp', 'gromacs/src/testutils/testfileredirector.cpp/testfileredirector.cpp', 'gromacs/src/testutils/filematchers.cpp/filematchers.cpp', 'gromacs/src/testutils/xvgtest.cpp/xvgtest.cpp']

FILES_TO_RUN = ['googletest/googletest/src/gtest-all.cc/gtest-all.cc']

import os

BASE_DIR = ""
PROBLEM_DOMAIN_FILE = "googletest/ProblemDomainConcepts.txt"

def PJ(dir):
	return os.path.join(BASE_DIR,dir)

for file in set(FILES_TO_RUN):
	basename = os.path.basename(file)
	file_without_extention = basename.split(".")[0]
	complete_path_file = PJ(file)
	complete_path_xml = complete_path_file[:-len(basename)]
	complete_path_xml += file_without_extention
	complete_path_xml += "_clang.xml"
	print("Running for file - ",file, complete_path_file, complete_path_xml)

	os.system("python2 XML_GetExcelForAFile.py " + complete_path_file + " Identifier/program_domain.csv "+ PROBLEM_DOMAIN_FILE +" " +complete_path_xml + " " + file)

# Run inside CSV folder if BASE_DIR starts with .. (because it will hidden then). Use ls -lrta to view the files in CSV folder.

# import shutil
# import os
# for file in os.listdir("."):
# 	if file.startswith(".._.._"):
# 		shutil.copy(file,file[6:])